export { default as ArrowRight } from './About/Icons/ArrowRight'
export * from './About'
export * from './Contact'
export { default as Home } from './Home'
export { default as PageNotFound } from './PageNotFound'
export { default as Signin } from './Signin'
export { default as Signup } from './Signup'
